# Generated by Django 5.0.1 on 2024-07-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_test_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='environment',
            field=models.CharField(choices=[('xbee', 'XBee'), ('sim', 'Simulation')], default='sim', max_length=24),
            preserve_default=False,
        ),
    ]
