# Generated by Django 5.0.7 on 2024-12-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_test_completed_test_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='environment',
            field=models.CharField(choices=[('xbee', 'XBee'), ('sim', 'Simulation'), ('bt', 'Bluetooth')], max_length=24),
        ),
    ]
